# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 60730ae2d898891f2c14662997a60d1e8bf40525f7f090d85d3592a6649c48c9cae4577a8eb8e978523838cb2ed83b6aca8b8a2f9c2c3bd506039aa80ddeda37

test:
  secret_key_base: 969611d4124013ea910c578eaa252918b2b500de0f58fd9e3e24a6023147b0d3de13241e47868058fdad49b643282fcf3d7f622996f91a989fb51294cba9bbc8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
#  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  secret_key_base: 969611d4124013ea910c578eaa252918b2b500de0f58fd9e3e24a6023147b0d3de13241e47868058fdad49b643282fcf3d7f622996f91a989fb51294cba9bbc8

